### ISSUE TITLE
Portainer pulls from Docker Hub fail

### ISSUE THREAD

**Issue by truthsword** [wernerfred/docker-rainloop#57]
Should I update my docker-compose to reflect a new download path? Presently it is:
```
version: '3'
services:
  rainloop:
    image: wernerfred/docker-rainloop:latest
    container_name: rainloop
    restart: always
    ports:
      - 80:80
    volumes:
      - ./rainloop/:/rainloop/data
```
So it defaults to Docker Hub. Thanks!
